baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Labyrinthe Rules'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[menu]
[[menu.after]]
  name = "Labyrinthe Website"
  url = "http://www.labyrinthe.co.uk"
  weight = 100

[params]
    BookLogo = 'LabyrintheLogo.png'
    BookSection = 'books'
    BookToc = true
    BookRepo = 'https://github.com/labyrinthe/rulebooks'

[markup]
  [tableOfContents]
    endLevel = 4